apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-fs
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  storageClassName: standard
    
